### ISSUE TITLE
How to achieve this in the apns push notification?  

### ISSUE THREAD

**Issue by ArunVicky001** [Guerrix/Custom-Notification-Groups-Demo#1]
Hi, 

Your sample works well, I want to implement the same in the real push notification. 
example in my apns payload what should I need to add? 

{
            "google.c.sender.id" : "449231484161" ,
            "aps" : { "alert" :     {
                "body" : "direct message",
                "title: : "New direct message"
            },
                "category" : "notification-screen",
                "sound" : "default"
            } ,
            "click_link" : "https://www.google.com",
            "time_to_live" : "3600" ,
            "google.c.fid" : "DntsppGY" ,
            "google.c.a.e" : "1" ,
            "gcm.message_id" : "1708430998299305"
        }
{

**Comment by Guerrix** [comment]
You need to provide the `threadIdentifier` according to [apple documentation](https://developer.apple.com/documentation/usernotifications/unnotificationcontent/1649860-threadidentifier) you need to add  `thread-id` inside `aps`.  Also, please remember that if the user does not have the group configuration in iPhone settings, it won't matter.
